// <auto-generated />
using System;
using CardLimit.Core.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace CardLimit.Migrations
{
    [DbContext(typeof(CardDbContext))]
    [Migration("20210314130410_ChangeColumnPriority")]
    partial class ChangeColumnPriority
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("CardLimit.Core.Model.Card", b =>
                {
                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("AvailableBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardHolderName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("InitialBalance")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("CardId");

                    b.HasIndex("CardId")
                        .IsUnique();

                    b.ToTable("Card");
                });

            modelBuilder.Entity("CardLimit.Core.Model.Limit", b =>
                {
                    b.Property<int>("LimitId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("AggregateAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTimeOffset>("TransactionDate")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("LimitId");

                    b.HasIndex("CardId");

                    b.ToTable("Limit");
                });

            modelBuilder.Entity("CardLimit.Core.Model.Limit", b =>
                {
                    b.HasOne("CardLimit.Core.Model.Card", null)
                        .WithMany("Limits")
                        .HasForeignKey("CardId");
                });

            modelBuilder.Entity("CardLimit.Core.Model.Card", b =>
                {
                    b.Navigation("Limits");
                });
#pragma warning restore 612, 618
        }
    }
}
